version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: finpay-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - finpay-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:15
    container_name: finpay-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Murad3645
      POSTGRES_DB: FinPayDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finpay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finpay-api
    ports:
      - "5291:5290"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FinPayDb;Username=postgres;Password=Murad3645
      - RabbitMq__Host=finpay-rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    networks:
      - finpay-network

  nginx:
    image: nginx:alpine
    container_name: finpay-nginx
    depends_on:
      - app
    ports:
      - "8083:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - finpay-network

networks:
  finpay-network:
    driver: bridge

volumes:
  pgdata:
